app:
  doc:
    version: First
    title: Class Project
    description: Calendar App
    terms-of-service: http://swagger.io/terms/
    license:  Apache 2.0
    url: http://springdoc.org

spring:
  profiles:
    active: dev