# We are using the same commands as discussed in lecture in the terminal
# start:   docker-compose -f docker-dbonly.yml up -d
# create volume:   docker volume create calendar-db-postgres
# create volume:   docker volume create calendar-db-mongo
# stop:    docker-compose -f docker-dbonly.yml down


version: '3.8'
services:
  postgres:
    container_name: demo-postgres
    image: postgres
    env_file: ./.env
    volumes:
      - calendar-db-postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      POSTGRES_PASSWORD: $SQL_PASSWORD
  mongo:
    container_name: demo-mongo
    image: mongo
    env_file: ./.env
    volumes:
      - calendar-db-mongo:/data/db
    restart: always
    ports:
      - $MONGO_PORT:$MONGO_PORT