package com.group2.project.calendarobjects;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Getter;
import lombok.ToString;

import java.time.ZonedDateTime;
import java.util.Date;

// JZ: this class defines the structure for a base calendar 'event' object

@Data
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "EVENT_TYPE")
@Getter
public class CalendarObject
{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // changed this to work with FX:
    @Column(name = "DATE")
    private ZonedDateTime date;

    @Column(name = "TITLE")
    private String title;

    @Column(name = "DESC")
    private String description;

    // JZ: default constructor for lombok, not generated by itself?
    public CalendarObject()
    {

    }

    public CalendarObject(ZonedDateTime date, String title, String description) {
        this.date = date;
        this.title = title;
        this.description = description;
    }

    @Override
    public String toString() {
        return "CalendarObject{" +
                "title='" + title + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}
