package com.group2.project.calendarobjects;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Getter;

import java.util.Date;

// JZ: this class defines the structure for a base calendar 'event' object

@Data
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "EVENT_TYPE")
@Getter
public class CalendarObject
{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "DATE")
    private Date date;

    @Column(name = "TITLE")
    private String title;

    @Column(name = "DESC")
    private String description;

    // JZ: default constructor for lombok, not generated by itself?
    public CalendarObject()
    {

    }

    public CalendarObject(Date date, String title, String description) {
        this.date = date;
        this.title = title;
        this.description = description;
    }

}
